name: gambau
description: Tools for generate app icons for the Flutter projects.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.13.0-0 <3.0.0'

dependencies:
  args: ^2.3.0
  image: ^3.0.8
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
