name: gedabak
description: Tools for managing Dart and/or Flutter projects.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.13.0-0 <3.0.0'

dependencies:
  args: ^2.3.0
  meta: ^1.7.0
  path: ^1.8.0
  pub_api_client: ^2.1.1
  pub_semver: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1