name: gedabak
description: Tools for managing Dart and/or Flutter projects.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  args: ^2.4.2
  meta: ^1.12.0
  path: ^1.9.0
  pub_api_client: ^2.7.0
  pub_semver: ^2.1.4
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0